/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

/**
 * This is the mainApp.
 */
public class App {
  /**
   * MainClass.
   *
   * @param args
   *
   */
  public static void main(String[] args) {
    //System.out.println("Working Directory = " + System.getProperty("user.dir"));
    App newApp = new App();
    String greeting = newApp.getGreeting();
    System.out.println(greeting);
    Menu menu = new Menu();
    menu.run();
  }

  /**
   * getGreeting(teste).
   *
   * @return
   *
   */

  public String getGreeting() {
    return "Welcome to the Solar System dear user!";
  }
}
